language: node_js

dist: trusty

sudo: false

node_js:
  - "node"

addons:
  firefox: latest
  chrome: stable
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - clang-format-3.7
      - pep8
      - python2.7
      - pylint
      - python3
      - python3-pip

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xf geckodriver-v0.19.1-linux64.tar.gz -C geckodriver
  - wget https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
  - mkdir chromedriver
  - unzip chromedriver_linux64.zip chromedriver -d chromedriver
  - export PATH=$PATH:$PWD/geckodriver:$PWD/chromedriver
  - pip install --user six
  - pip install --user https://github.com/google/closure-linter/zipball/master
  - pip3 install --user selenium
  - pip3 install --user pytest

script:
  - npm test
  - python2.7 libkarel/libkarel_test.py
  - python3 -m pytest test/ --browser=firefox
  - pylint --rcfile=libkarel/.pylintrc libkarel/libkarel.py libkarel/libkarel_test.py
  - pep8 --ignore=E501 libkarel/libkarel.py libkarel/libkarel_test.py test/conftest.py test/test_webdriver.py
  - hook_tools/lint.py validate --all
